/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.danimo.frames;

import com.danimo.ParserHandleSecure;
import com.danimo.manageError.ObjectErr;
import com.danimo.manageError.TypeSecureError;
import com.danimo.objects.NumeroLinea;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author danimo
 */
public class EditorPanel extends javax.swing.JPanel {
    private static ArrayList<ObjectErr> errorForClient= TypeSecureError.getTypeErrorSingleton().errores;
    NumeroLinea numeroLinea;
    public String currentFilePath;
    /**
     * Creates new form EditorPanel
     */
    public EditorPanel(String text, String path) {
        initComponents();
        buttom_compilar.setBackground(Color.green);
        numeroLinea= new NumeroLinea(jTextArea1);
        jScrollPane1.setRowHeaderView(numeroLinea);
        jTextArea2.setEnabled(false);
        line.setText("Linea: 0");
        column.setText("Columna: 0");
        jTextArea1.setText(text);
        this.currentFilePath= path;
    }

    public void obtenerPosicion(String codigo ) {
    // separar el código por líneas
         String[] lineas= codigo.split("\n");
        line.setText("Linea: "+ lineas.length);
        if(lineas.length >0){
             column.setText("Columna: "+lineas[codigo.split("\n").length-1].length());
        }else{
            column.setText("Columna: 0");
        }    
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        line = new javax.swing.JLabel();
        column = new javax.swing.JLabel();
        buttom_compilar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        line.setText("jLabel1");

        column.setText("jLabel2");

        buttom_compilar.setText("Compilar");
        buttom_compilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttom_compilarActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 945, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 945, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(line)
                        .addGap(18, 18, 18)
                        .addComponent(column)
                        .addGap(223, 223, 223)
                        .addComponent(buttom_compilar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(504, 504, 504)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(line)
                    .addComponent(column)
                    .addComponent(buttom_compilar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
        // TODO add your handling code here:
         this.obtenerPosicion(jTextArea1.getText());
    }//GEN-LAST:event_jTextArea1KeyPressed

    private void buttom_compilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttom_compilarActionPerformed
        // TODO add your handling code here:
        errorForClient.clear();
        jTextArea2.setText("");
        System.out.println("Compillando "+ jTextArea1.getText());
        System.out.println("vamos a compilar");
        String texto= jTextArea1.getText();
        
        if(texto!= "" && !texto.isEmpty()){
             ParserHandleSecure.compilerSecure(texto);
        }else{
            JOptionPane.showMessageDialog(this, "Necesitas ingresar texto primero");
        }
       
    }//GEN-LAST:event_buttom_compilarActionPerformed

    public  String getPath(){
        return this.currentFilePath;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buttom_compilar;
    public javax.swing.JLabel column;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextArea jTextArea2;
    public javax.swing.JLabel line;
    // End of variables declaration//GEN-END:variables
}
